services:
  - type: web
    name: hospital-info
    env: java
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/Hospital_info-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: PORT
        value: 8080
